remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [Jakarta Mail]
description: [Jakarta Mail Implementation]

links:
  source: https://github.com/eclipse-ee4j/mail
  javadocs: docs/api/
  download: https://github.com/eclipse-ee4j/mail/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/mail-dev
  faq: FAQ

include:
  - LICENSE.md
  - CONTRIBUTING.md
